### ISSUE TITLE
Raspberry Pi 4 config

### ISSUE THREAD

**Issue by sighmon** [brutella/hkcam#89]
I was struggling with the error from `cat /var/log/hkcam/current`:

```bash
2020-07-23_13:44:40.23375 [video4linux2,v4l2 @ 0x238d200] Cannot open video device /dev/video1: No such file or directory
```

So I modified the `ansible/roles/hkcam/tasks/configure.yml` to a newer `v0.12.5` release of `v4l2loopback`:

```yml
# ansible/roles/hkcam/tasks/configure.yml

- name: Download v4l2loopback
  get_url:
     url: https://github.com/umlaeute/v4l2loopback/archive/v0.12.5.tar.gz
     dest: /tmp
  register: v4l2_pkg_download
```

I then stopped the service on the Raspberry Pi with `sudo sv stop hkcam` and re-ran the ansible playbook on macOS `ansible-playbook rpi.yml -i hosts --ask-pass`.

This still didn't seem to work, as I still didn't have `/dev/video1`, so I re-ran the modprobe command:

```bash
sudo sv stop hkcam
sudo modprobe v4l2loopback
sudo sv start hkcam
```

After that it created `/dev/video1` and I could get the video streaming.

It's a bit late at night here to see if re-running modprobe would have fixed it without having to install `v0.12.5`, but in any case this is what worked for me.
